[package]
name = "rapidquilt"
version = "0.4.2"
authors = ["Michal Srb <michalsrb@gmail.com>"]
edition = '2018'

[profile.release]
lto = true

[dependencies]
colored = "1.6"
isatty = "0.1"
rayon = "1.0"
getopts = "0.2"
failure = "0.1"
memchr = "2.1"
seahash = "3.0"
smallvec = "0.4"
libc = "0.2"
nom = "4.1"

[features]
# Enable this feature to enable benchmarks using the (currently) unstable
# test::Bencher.
bencher = []
