[package]
name = "rapidquilt"
version = "0.1.0"
authors = ["Michal Srb <michalsrb@gmail.com>"]

[profile.release]
lto = true

[dependencies]
# crossbeam-channel = "0.3"
# crossbeam-utils = "0.6"
crossbeam = "0.5"
failure = "0.1"
seahash = "3.0"
lazy_static = "1.2"
libc = "0.2"
regex = "1"
