[package]
name = "rapidquilt"
version = "0.5.1"
authors = ["Michal Srb <michalsrb@gmail.com>"]
edition = '2018'

[profile.release]
lto = true

[lib]
name = "libpatch"
path = "src/libpatch/lib.rs"

[[bin]]
name = "rapidquilt"
path = "src/rapidquilt/main.rs"

[dependencies]
colored = "1"
derive_builder = "0.7"
failure = "0.1"
getopts = "0.2"
indexmap = "1"
atty = "0.2"
libc = "0.2"
memchr = "2"
nom = "4"
pathfinding = "1"
rayon = "1"
seahash = "3"
smallvec = "0.6"
strsim = "0.8"

[features]
# Enable this feature to enable benchmarks using the (currently) unstable
# test::Bencher.
bencher = []
